import type { Radar as RadarShape } from "~/types/radar.js";
export const data = {
	title: "Radar",
	rings: [
		{ id: "rng-1", name: "Adopt", color: "#93c47d" },
		{ id: "rng-2", name: "Trial", color: "#76a5af" },
		{ id: "rng-3", name: "Assess", color: "#f6a82b" },
		{ id: "rng-4", name: "Hold", color: "#e06666" },
		{ id: "rng-5", name: "Avoid", color: "#f4f" },
	],
	sections: [
		{ id: "sec-1", name: "Languages & Frameworks" },
		{ id: "sec-2", name: "Data Management" },
		{ id: "sec-3", name: "Infrastructure & Operations" },
		{ id: "sec-4", name: "Security" },
		{ id: "sec-5", name: "Development Tools" },
	],
	entries: [
		{
			name: "TypeScript",
			sectionId: "sec-1",
			ringId: "rng-1",
			isNew: false,
			description: "A popular typed superset of JavaScript.",
			link: "https://www.typescriptlang.org/",
			moved: 1,
		},
		{
			name: "GraphQL",
			sectionId: "sec-2",
			ringId: "rng-2",
			isNew: true,
			description:
				"A query language for APIs and a runtime for executing those queries.",
			link: "https://graphql.org/",
			tags: ["API", "data"],
			moved: 0,
		},
		{
			name: "Docker",
			sectionId: "sec-3",
			ringId: "rng-1",
			isNew: false,
			description:
				"A platform for developing, shipping, and running applications in containers.",
			link: "https://www.docker.com/",
			tags: ["containers", "devops"],
			moved: 0,
		},
		{
			name: "OWASP ZAP",
			sectionId: "sec-4",
			ringId: "rng-3",
			isNew: false,
			description: "An open-source web application security scanner.",
			link: "https://www.zaproxy.org/",
			tags: ["security", "web"],
			moved: -1,
		},
		{
			name: "VS Code",
			sectionId: "sec-5",
			ringId: "rng-1",
			isNew: false,
			description: "A powerful and extensible code editor.",
			link: "https://code.visualstudio.com/",
			tags: ["IDE", "tools"],
			moved: 0,
		},
		{
			name: "Python",
			sectionId: "sec-1",
			ringId: "rng-1",
			isNew: false,
			description: "A versatile and popular programming language.",
			link: "https://www.python.org/",
			tags: ["language", "popular"],
			moved: 0,
		},
		{
			name: "PostgreSQL",
			sectionId: "sec-2",
			ringId: "rng-1",
			isNew: false,
			description: "An advanced open-source relational database.",
			link: "https://www.postgresql.org/",
			tags: ["database", "SQL"],
			moved: 0,
		},
		{
			name: "Kubernetes",
			sectionId: "sec-3",
			ringId: "rng-2",
			isNew: true,
			description:
				"An open-source system for automating deployment, scaling, and management of containerized applications.",
			link: "https://kubernetes.io/",
			tags: ["orchestration", "cloud"],
			moved: 1,
		},
		{
			name: "Snyk",
			sectionId: "sec-4",
			ringId: "rng-3",
			isNew: true,
			description:
				"A tool for identifying and fixing vulnerabilities in your code and dependencies.",
			link: "https://snyk.io/",
			tags: ["security", "dependencies"],
			moved: 1,
		},
		{
			name: "GitHub Copilot",
			sectionId: "sec-5",
			ringId: "rng-2",
			isNew: true,
			description: "An AI-powered code completion tool.",
			link: "https://copilot.github.com/",
			tags: ["AI", "tools"],
			moved: 0,
		},
		{
			name: "Rust",
			sectionId: "sec-1",
			ringId: "rng-2",
			isNew: true,
			description:
				"A programming language focused on performance and memory safety.",
			link: "https://www.rust-lang.org/",
			tags: ["language", "safe"],
			moved: 1,
		},
		{
			name: "MongoDB",
			sectionId: "sec-2",
			ringId: "rng-3",
			isNew: false,
			description: "A NoSQL database for modern applications.",
			link: "https://www.mongodb.com/",
			tags: ["NoSQL", "database"],
			moved: -1,
		},
		{
			name: "Terraform",
			sectionId: "sec-3",
			ringId: "rng-2",
			isNew: false,
			description:
				"An infrastructure as code (IaC) tool for managing cloud resources.",
			link: "https://www.terraform.io/",
			tags: ["IaC", "cloud"],
			moved: 0,
		},
		{
			name: "Burp Suite",
			sectionId: "sec-4",
			ringId: "rng-2",
			isNew: false,
			description: "A suite of tools for web application security testing.",
			link: "https://portswigger.net/burp",
			tags: ["security", "testing"],
			moved: 1,
		},
		{
			name: "JetBrains IntelliJ IDEA",
			sectionId: "sec-5",
			ringId: "rng-3",
			isNew: false,
			description: "A feature-rich IDE for Java and other languages.",
			link: "https://www.jetbrains.com/idea/",
			tags: ["IDE", "tools"],
			moved: -1,
		},
		// Add items in ring 4 & 5 pls
		{
			name: "AngularJS",
			sectionId: "sec-1",
			ringId: "rng-4",
			isNew: false,
			description: "A structural framework for dynamic web apps.",
			link: "https://angularjs.org/",
			tags: ["framework", "javascript"],
			moved: -1,
		},
		{
			name: "MySQL",
			sectionId: "sec-2",
			ringId: "rng-4",
			isNew: false,
			description: "An open-source relational database management system.",
			link: "https://www.mysql.com/",
			tags: ["database", "SQL"],
			moved: -1,
		},
		{
			name: "Chef",
			sectionId: "sec-3",
			ringId: "rng-4",
			isNew: false,
			description:
				"A configuration management tool for automating infrastructure.",
			link: "https://www.chef.io/",
			tags: ["automation", "devops"],
			moved: -1,
		},
		{
			name: "Nessus",
			sectionId: "sec-4",
			ringId: "rng-4",
			isNew: false,
			description: "A vulnerability scanner for identifying security issues.",
			link: "https://www.tenable.com/products/nessus",
			tags: ["security", "vulnerability"],
			moved: -1,
		},
		{
			name: "Eclipse",
			sectionId: "sec-5",
			ringId: "rng-4",
			isNew: false,
			description: "An IDE for Java development.",
			link: "https://www.eclipse.org/",
			tags: ["IDE", "tools"],
			moved: -1,
		},
		{
			name: "Backbone.js",
			sectionId: "sec-1",
			ringId: "rng-5",
			isNew: false,
			description:
				"A lightweight JavaScript library for structuring web applications.",
			link: "https://backbonejs.org/",
			tags: ["framework", "javascript"],
			moved: -1,
		},
		{
			name: "CouchDB",
			sectionId: "sec-2",
			ringId: "rng-5",
			isNew: false,
			description: "A NoSQL database that uses JSON for documents.",
			link: "https://couchdb.apache.org/",
			tags: ["NoSQL", "database"],
			moved: -1,
		},
		{
			name: "Puppet",
			sectionId: "sec-3",
			ringId: "rng-5",
			isNew: false,
			description: "An open-source software configuration management tool.",
			link: "https://puppet.com/",
			tags: ["automation", "devops"],
			moved: -1,
		},
		{
			name: "Nikto",
			sectionId: "sec-4",
			ringId: "rng-5",
			isNew: false,
			description: "An open-source web server scanner.",
			link: "https://cirt.net/Nikto2",
			tags: ["security", "scanner"],
			moved: -1,
		},
		{
			name: "NetBeans",
			sectionId: "sec-5",
			ringId: "rng-5",
			isNew: false,
			description: "An IDE for Java development.",
			link: "https://netbeans.apache.org/",
			tags: ["IDE", "tools"],
			moved: -1,
		},
	],
} satisfies RadarShape;
